# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-build

# Trigger the workflow when:
on:
  push:
  pull_request:

# Explicitly disable secrets.GITHUB_TOKEN permissions.
permissions: {}

jobs:
  build:
    # NOTE: This name appears in GitHub's Checks API.
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Set workflow variables
        # Id is needed to access output in a next step.
        id: vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Build app
        run: yarn build:ext
      - name: Upload build artifacts
        # Upload build artifacts on push event.
        uses: actions/upload-artifact@v3
        with:
          name: oasis-wallet-web-${{ steps.vars.outputs.SHORT_SHA }}
          path: build-ext
