# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-test

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - master
      - stable/*

# Explicitly disable secrets.GITHUB_TOKEN permissions.
permissions: {}

jobs:
  yarn_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        id: yarn-cache
        with:
          node-version: 18
          cache: yarn
      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  playwright:
    # NOTE: This name appears in GitHub's Checks API.
    name: playwright
    needs: [yarn_cache]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: REACT_APP_E2E_TEST=1 yarn build:ext
      - run: REACT_APP_E2E_TEST=1 yarn start:prod &
      - name: Install playwright's npm dependencies
        working-directory: ./playwright/
        run: yarn install --frozen-lockfile
      - name: Install playwright's system dependencies
        working-directory: ./playwright/
        run: npx playwright install --with-deps
      - run: npx wait-on http://localhost:5000/ --timeout 60000
      - name: Run playwright tests (with xvfb-run to support headed extension test)
        working-directory: ./playwright/
        run: BASE_URL=http://localhost:5000 EXTENSION_PATH=../build-ext/ xvfb-run yarn test
      - name: 'Upload playwright test-results'
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          path: playwright/test-results
          retention-days: 5
